# GitHub Actions Workflow for Quality Report Generation
# 品質レポート自動生成のワークフロー例

name: Quality Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  quality_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=src/ --cov-report=xml:coverage.xml --cov-report=html:htmlcov
      - name: Run static analysis (Pylint)
        run: |
          pylint src/ --exit-zero --output-format=json:pylint-report.json || echo "Pylint found issues, but we proceed."
      # ...（必要に応じてBandit, Semgrep, pip-audit等も追加）
      - name: Generate dashboard data
        run: python scripts/generate_dashboard.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dashboard_output 